package com.gadawski.app

import com.gadawski.util.facts.*;
import java.math.BigDecimal;

global com.gadawski.util.common.Counter counter;

/**
 *	Nastepujaca regula sprawdza ilosc pieniedzy, ktora posiada klient,
 *	a takze cene obiektu typu Car oraz House. W przypadku
 *	spelnienia warunkow nastepuje stworzenie propozycji klientowi.
 */
 /**
 *	Example rule that checks if customer has enough money 
 *	and if there is car that can be proposed to him.
 *	If conditions are met, car proposal is created 
 *	and inserted into the KnowledgeSession.
 *	
 *	@author l.gadawski@gmail.com
 */
 /**/
rule "Are U rich"
    when
        customer : Customer ( cash >= 20000  )
      	car : Car ( price > 2000 )
        house : House ( price > 20000 )
    then
        System.out.println( counter.getAndIncrement() );
        modify(car) {
        	setName( "lukaszek" ),
        	setPrice( new BigDecimal(888));
        };
        System.out.println( "spoksik" );
end
/**/

rule "1" 
	when 
		car : Car ( name == "lukaszek" )
		house : House ( price > 2000 )
	then
		System.out.println( "luki");
		insert(new Car("gad", new BigDecimal(888) ));
end


rule "2" 
	when 
		car : Car ( name == "gad" )
	then
		System.out.println( "sff" + " " + car.getPrice() );
end
/*
rule "1"
	when 
		$car : Car()
		//$customer : Customer()
		CarProposal(car == $car)//, customer == $customer)  
	then
		System.out.println("hej");
end
*/